### ISSUE TITLE
MSVC warning C6031: Return value ignored: '_fullpath', clove-unit.h(1005)

### ISSUE THREAD

**Issue by vbaderks** [fdefelici/clove-unit#113]
When including clove-unit.h with CLOVE_IMPLEMENTATION defined, MSVC will generate the error/warning:

`extern\clove-unit\clove-unit.h(1005): error C6031: Return value ignored: '_fullpath'.
`
https://github.com/fdefelici/clove-unit/blob/f723e549443160ffb6234c1923a8df3bb03fbe90/clove-unit.h#L1005

Note: At line 1004 there is already an alternative (commented out) line that does check the return value, which makes it unclear how to create a PR for this issue.

**Comment by fdefelici** [comment]
Hi @vbaderks thanks for reporting the issue

Could you share which configuration/flags your are using for MSVC to show up this warning?

Currently I've tested with:
- /W4: no issues are showed
- /Wall: shows a bunch of issue but no `C6031` (or `C26451` from the other issue #114 )

**Comment by vbaderks** [comment]
Hi @fdefelici,

The MSVC compiler has a build in static analyser. It has an old analyzer called PreFast and a new analyzer called EspXEngine that can also load additional extensions. Most functionality of the new analyzer only focuses on C++ however.

The warning range C6xxx are warnings from PreFast and the C2xxxx range is from the EspXEngine. The C6xxx warnings are actually the most useful for C applications. They are the most effective when annotating methods with SAL (standard annotation language). SAL is useful but the header file sal.h is only provided with the MSVC compiler and not with GCC or clang, so not really a "standard" solution.

I normally use MSBuild properties to turn the static analyzer on/off (enabling it makes compiling slower):
    \<RunCodeAnalysis\>true\</RunCodeAnalysis\>
    \<EnableMicrosoftCodeAnalysis\>true\</EnableMicrosoftCodeAnalysis\>
    \<CodeAnalysisRuleSet\>$(MSBuildThisFileDirectory)default.ruleset\</CodeAnalysisRuleSet\>

this will result in the following compiler flags:

- RunCodeAnalysis will set the compiler flag /analyze, which will enable the static analyzer (PreFast). 
- EnableMicrosoftCodeAnalysis will set the compiler flag /analyze:plugin"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\EspXEngine.dll" which will enable the new analyzer
- CodeAnalysisRuleSet will tell the EspX analyzer which rules to enable. This is a XML configuration file. It will set the flag:
/analyze:ruleset"C:\repos\netpbm-wic-codec-c\default.ruleset"

Note 1: I have upload my repo that uses clove-unit.h to https://github.com/vbaderks/netpbm-wic-codec-c if you need a working sample (warnings are enabled in release build). Note that clove-unit.h is already patched in my repo,
Note 2: the docs for the /analyze  switch are on: https://learn.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis
Note 3: Microsoft docs state that the /analyze switch only works in the Enterprise version of VS. But I don't think this is true anymore.

**Comment by fdefelici** [comment]
OK. I have replicated the issue using your configuration.

And I also confirm that `/analyze` flag works on VS Community 2022.

So to fix the issue, considering it is not needed to check for the returned value of `__fullpath` in this scenario, I could use `__CLOVE_UNUSED_VAR` macro to enforce this concept.

https://github.com/fdefelici/clove-unit/blob/f723e549443160ffb6234c1923a8df3bb03fbe90/clove-unit.h#L63

**Comment by vbaderks** [comment]
Using __CLOVE_UNUSED_VAR seems logical. In my patched local version I used raw (void). Only minor remark is that __CLOVE_UNUSED_VAR reads like that the code has an unused variable, while the intend is to ignore the returned result.

**Comment by fdefelici** [comment]
Yes, you are right.
I had the same thought, but I didn't write it down because I was actually thinking about two solutions.

**First solution** 
Wrapping the function call.  
```
__CLOVE_UNUSED_VAR(_fullpath(...))
```
So in this case to make more clear the intent something like this could be better:
`__CLOVE_UNUSED_VALUE`  (or similar)

**Second solution**
Assign the result to a variable and then mark that variable as unused:
```
char* result = _fullpath(...);
__CLOVE_UNUSED_VAR(result);
```

Probably, I like more the second solution to avoid the "wrap" of the function call that could lead to poor code readibility.
