### ISSUE TITLE
Remark: clove_unit.h defines identifiers from the reserved C namespace

### ISSUE THREAD

**Issue by vbaderks** [fdefelici/clove-unit#115]
Just a remark:

The C standard has the statement:

_Some identifiers are reserved.
All identifiers that begin with a double underscore (__) or begin with an underscore (_) followed by an uppercase letter are reserved for any use, except those identifiers which are lexically identical to keywords._

double underscores are used in clove_unit.h, for example __CLOVE_PATH_SEPARATOR, __clove_path_is_absolute, etc.

Some static analyzer (like Sonar, clang-tidy, clang with -Wreserved-identifier) can complain about this. 

Note: detailed info: https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier

**Comment by fdefelici** [comment]
Yes, you're right.
I'm aware of that but considering that is just a test library (so nothing that fit in the production code), I took some liberties :)(considering that some rules exclusion can be possible for the test binary).

Anyhow, It is something that could be improved to be strictly compliant to the coding-standards and replace `__` prefix with something like `p__` or `p_`
