### ISSUE TITLE
CmdLine: Add list tests flag to print suites/tests and code location

### ISSUE THREAD

**Issue by aey76** [fdefelici/clove-unit#32]
consider this (not fully complete) implementation:

``` C
#define AS_STRING(x) #x

#define __CLOVE_SUITE_CALL_METHOD_AUTO_2(suite, title, param) __clove_sym___##suite##___##title(param)
#define __CLOVE_SUITE_CALL_METHOD_AUTO_1(suite, name, param) __CLOVE_SUITE_CALL_METHOD_AUTO_2(suite, name, param)
#define __CLOVE_SUITE_PRINT_METHOD_AUTO(suite, name) printf("%s %s %s %d\n", AS_STRING(suite), #name, __FILE__, __LINE__)

#define __CLOVE_TEST_AUTO(title) \
	__CLOVE_SUITE_METHOD_AUTO_1( CLOVE_SUITE_NAME, 30_ ## title, __clove_test_t *_this); \
	__CLOVE_SUITE_METHOD_AUTO_1( CLOVE_SUITE_NAME, 20_ ## title, __clove_test_t *_this) { \
		if (print_tests) \
			__CLOVE_SUITE_PRINT_METHOD_AUTO(CLOVE_SUITE_NAME, title); \
		else \
			__CLOVE_SUITE_CALL_METHOD_AUTO_1(CLOVE_SUITE_NAME, 30_ ## title, _this); \
	} \
	__CLOVE_SUITE_METHOD_AUTO_1( CLOVE_SUITE_NAME, 30_ ## title, __clove_test_t *_this)
```

when `print_tests` is `true` we will get print output of all the tests and when `print_tests` is `false` the tests will run as usaul.

**Comment by fdefelici** [comment]
Hi @aey76 ,

I understand technically the feature you are asking for, and I would like to understand better what would be your use case, and if it could be a general purpose one.

So could you explain further why do you need to print the list of Suite/Test (and related metadata)?

**Comment by aey76** [comment]
The basic need is to tell the tests in givven executable without the source code and without executing the tests, just to know what tests are in the executable, this is also handy for general test runners that will be able to get the list of tests and populate the test tree GUI, this is very common with other (cpp) unit test framworks like gtest, catch2 and boost test.

The additional meta data will simply alow the vscode extension to know the test locations without scanning the source code.

**Comment by fdefelici** [comment]
OK. I see.
This was something I reasoned about, for the implementation of the vscode extension, but in the end I opted for source scanning to have a more "responsive"  test tree UI, in terms of discovery CRUD operations the use does on suites/tests.

Anyway this feature could be useful not only for creating UI Adapters, but also could make sense for automation, so it is general purpose enough to be put in the backlog.

I mark this issue as a feature and I'll evaluate to put it in the next release/milestone.

**Comment by fdefelici** [comment]
Example of command to collect test lists from a clove unit binary.
Output is a CSV with following data: Suite Name, Test Name, Source File, Line Number
NOTE: With this command can optionally be used include/exclude expression already available when running tests (https://github.com/fdefelici/clove-unit/tree/v2.2.4#console-apis)

**Command**
```
<executable> --list-tests [-i include_expr] [-e exclude_expr]
```

**Result**
```
CmdTestListTest,ListAllTestsTest,src\inte\testlist_test.c,23
CmdTestListTest,ListTestWithExclusionTest,src\inte\testlist_test.c,44
CmdTestListTest,ListTestWithInclusionTest,src\inte\testlist_test.c,35
InvalidCmdTest,InvalidDash,src\inte\cmd_invalid_test.c,17
InvalidCmdTest,InvalidDashOneLetter,src\inte\cmd_invalid_test.c,23
InvalidCmdTest,InvalidDashTwoLetters,src\inte\cmd_invalid_test.c,29
InvalidCmdTest,InvalidDoubleDash,src\inte\cmd_invalid_test.c,35
InvalidCmdTest,InvalidDoubleDashParam,src\inte\cmd_invalid_test.c,41
RunTest,ConsoleReportIncludeOneTest,src\inte\run_test.c,38
RunTest,ConsoleReportIncludeTwoTest,src\inte\run_test.c,47
...
```

@aey76 This should cover the need. What do you think?

**Comment by fdefelici** [comment]
by issue #40 adding following output format:
- pretty print
- json
- csv

With option to print on stdout or file

**Comment by aey76** [comment]
looking good and together with #40 it's really awesome. thanks.
