### ISSUE TITLE
Assertion: Add GT/GTE/LT/LTE assertions for numeric types

### ISSUE THREAD

**Issue by DoctorWho406** [fdefelici/clove-unit#53]
Idea is to provide additional assertions when dealing with numeric  types: Greater Than, Greater than or Equal, Less Than, Less than or Equals ...

Understand if make sense or not.

**Comment by fdefelici** [comment]
More generic purpose respect to #43 (and similar to #44). 

All the issue share same doubt about if could make sense or not. From the POV of the user the answer will be probably yes. 
For clove-unit development  instead is more a combinatory explosion of assertion methods (that then need to be reflected also in related vscode and visual studio plugin).

Still thinking about it :)

**Comment by fdefelici** [comment]
Another reasoning I made in the past, was also that probably assertion like GT, GTE etc... are not good for testing purpose.
When writing test 99% of the time (if not 100%)  you should assert against a deterministic result. So in this case is very easy to convert the test from a GT to EQ. 
Only case where GT and similar could be needed is when testing against some random generation function eventually (but even random generation could be predicted most of the time)

@DoctorWho406 do you have any use case where this kind of assertion are useful?

**Comment by DoctorWho406** [comment]
I opened this issue mainly presenting two use cases:

1. Working with random numbers: having control over GT, GTE ... can be handy compared to using assertions like CLOVE_IS_TRUE(random_number > desired_number)
2. Avoid code repetitions: if the test has to check that one number is greater than another, the user can use the same line of code (GT) even if the value is computable.
For example I used CLOVE-UNIT to test my data structure; I needed to check that after a certain amount of operations, and regardless of the initial capacity, there was always enough space to allocate AT LEAST one new item. In the tests I had to recalculate the available memory each time and use CLOVE_UINT_EQ (remaining_memory, calculated_memory) with the risk of miscalculating when I could have used CLOVE_UINT_GT(remaining_memory, memory_one_item) duplicating the check for all tests

However, I leave to you the assessments of feasibility and usefulness @fdefelici

**Comment by fdefelici** [comment]
Almost sure that this will lead to poor test cases in terms of robustness, but I can give it a try.

Here the full list of macros that should be implemented:
||||||
|----|----|----|----|----|
| CLOVE_CHAR_GT<br>CLOVE_CHAR_GTE<br>CLOVE_CHAR_LT<br> CLOVE_CHAR_LTE | CLOVE_INT_GT<br>CLOVE_INT_GTE<br>CLOVE_INT_LT<br> CLOVE_INT_LTE | CLOVE_UINT_GT<br>CLOVE_UINT_GTE<br>CLOVE_UINT_LT<br> CLOVE_UINT_LTE | CLOVE_LONG_GT<br>CLOVE_LONG_GTE<br>CLOVE_LONG_LT<br> CLOVE_LONG_LTE | CLOVE_ULONG_GT<br>CLOVE_ULONG_GTE<br>CLOVE_ULONG_LT<br> CLOVE_ULONG_LTE |
| CLOVE_LLONG_GT<br>CLOVE_LLONG_GTE<br>CLOVE_LLONG_LT<br> CLOVE_LLONG_LTE | CLOVE_ULLONG_GT<br>CLOVE_ULLONG_GTE<br>CLOVE_ULLONG_LT<br> CLOVE_ULLONG_LTE | CLOVE_SIZET_GT<br>CLOVE_SIZET_GTE<br>CLOVE_SIZET_LT<br> CLOVE_SIZET_LTE | CLOVE_FLOAT_GT<br>CLOVE_FLOAT_GTE<br>CLOVE_FLOAT_LT<br> CLOVE_FLOAT_LTE | CLOVE_DOUBLE_GT<br>CLOVE_DOUBLE_GTE<br>CLOVE_DOUBLE_LT<br> CLOVE_DOUBLE_LTE | 
| CLOVE_PTR_GT<br>CLOVE_PTR_GTE<br>CLOVE_PTR_LT<br> CLOVE_PTR_LTE |
