### ISSUE TITLE
Suggestion: Remove semicolons in public assertions

### ISSUE THREAD

**Issue by vonhoff** [fdefelici/clove-unit#61]
In the current implementation, all public assertions end with semicolons, leading to empty statements when assertions are followed by semicolons, as shown in the sample code and screenshot below:

![image](https://github.com/fdefelici/clove-unit/assets/55744345/4627bb22-3de8-4d69-906b-487d1273483f)

To address this issue, one solution would be to remove semicolons from public assertions, requiring developers to use semicolons after assertions. However, this change would have an impact on developers who have not previously used semicolons after their assertions in order to avoid empty statements.

Another potential solution is to update the documentation and sample code to indicate that semicolons are not required after assertions.

**Comment by fdefelici** [comment]
To evaluate if enclosing assertion macro body between curly brakets could  prevent this kind of warning. 

Example:

```
#define CLOVE_IS_TRUE(v) { ... } 
```

**Comment by fdefelici** [comment]
@vonhoff which ide/linter are you using?

I'm trying to reproduce the issue using this simple example, using GCC and CLANG compiler with all warnings flags enabled (-Wextra -Wall), without any luck.

```
#define MACRO() puts("MacroEndedWithSimicolumn");

int main() {
    MACRO();
}
```

**Comment by vonhoff** [comment]
I use CLion as my IDE, I'm at work right now so I can't see the linter settings it uses. I will let you know later this afternoon.

**Comment by fdefelici** [comment]
After some reasoning the cleanest approach is to enclose assertion body within a do/while block to force multiple statements to behave as one. And obviously omitting the semicolon at the end. So an error, demanding for semicolon, will be shown at compile time.

```
#define CLOVE_IS_TRUE(v) do { ... } while(0)
```

Eventual regression for users should have low impact, considering that on documentation assertion example are ended by semicolon, and even eventually fix it is simple enough.

Anyway labelling this ticket as potential breaking change (but very low impact)
