### ISSUE TITLE
Double allocation in __clove_path_basepath

### ISSUE THREAD

**Issue by vonhoff** [fdefelici/clove-unit#62]
`__clove_path_basepath` uses strdup and calloc. This results in two separate memory allocations, which is inefficient and may cause memory fragmentation. A better approach would be to use only one allocation as mentioned in the function itself.
See: [clove-unit.h#L818](https://github.com/fdefelici/clove-unit/blob/d43981b346bfe374cbff6958092daa72aa2611c4/clove-unit.h#L818)

**Comment by fdefelici** [comment]
In this case perf and Memory frag are not really an issue, but would be nice if we find a way to improve it without loose code clarity.
