### ISSUE TITLE
Run Pretty: Automatically expand row length to the longest suite+test name

### ISSUE THREAD

**Issue by fdefelici** [fdefelici/clove-unit#88]
Currently aligment (with dot character) is hardcoded.
![image](https://github.com/fdefelici/clove-unit/assets/24794993/d364293e-ff77-493a-8954-58b9d09e21ec)

Eventually allow the user to specify the amount of aligment in case where some "Suite.Test" are not entirely visible.
![image](https://github.com/fdefelici/clove-unit/assets/24794993/03f4a511-a99d-45c3-b0e4-bb177909712e)

Or eventually evaluate the possibility to automatically align to the longest "Suite.Test" string

**Comment by vonhoff** [comment]
I almost wanted to create a new issue for this, as I just came across it in my own suites. It is good to see that it has already been noticed, I would like to see this in the next release. 

I think it would be an idea to be able to define a minimum length and a maximum length, where the final length is determined by the length of the longest Suite.Test, capped by the given range. What do you think?

**Comment by fdefelici** [comment]
"range" should be feasible. This will require to handle 2 params. 

Just wondering if handling this kind of configuration is really helpful instead of just having the line automatically adjust itself (so the user doesn't have to think about it) :)

**Comment by vonhoff** [comment]
I agree, automatically adjusting the line is a better approach to keep things simple. I attempted to write a simple implementation to get the longest entry name from all suites in addition to their test names. I have not figured out the best way to pass the resulting value through the necessary functions.

I wrote the following draft to run at the beginning of  `__clove_exec_suites`:
```c
size_t test_entry_length = 0;

for (size_t i = 0; i < suite_count; ++i) {
    __clove_suite_t* suite = &suites[i];
    size_t suite_length = strlen (suite->name);
    for (size_t j = 0; j < suite->test_count; j++) {
        __clove_test_t* test = (__clove_test_t*)__clove_vector_get(&suite->tests, j);
        size_t entry_length = suite_length + strlen(test->name) + 1; // +1 for the dot between suite and test name.
        if (entry_length > test_entry_length) {
            test_entry_length = entry_length;
        }
    }
}
```

The functions that would use this value instead of `__CLOVE_TEST_ENTRY_LENGTH` are:

- `__clove_report_pretty_end_test`
- `__clove_report_pretty_pad_right`

Edit: I just realized that it needs an additional value, as it seems that we need to consider the string length of texts like `[PASS]` too. However, I think it's a good start.

**Comment by fdefelici** [comment]
Need to reason a bit about it, because this feature is mostly related to the pretty report. So, it should not affect the general algorithm in `__clove_exec_suites`.

Now, pretty report is produced "on the go" while iterating tests in "full mode", whilst is produced "post tests iteration" in "failed+skipped mode".  (This distiction was done just to preserve performance for the main scenario "full mode" where all tests need to be printed - so basically iterating them once -, while in "failed+skipped  mode" tests are basically iterated twice)

In "post test iteration" should be easy to find the longest test name. 
So, can be evaluated to convert also "full mode" report production to be "post tests iteration".

**Comment by fdefelici** [comment]
Row alignement implemented with this logic:
- when max "Suite name + Test name" length is less then 50 characters is padded to 50 characters
- otherwise, the max is took as reference + 3 more chars (to have at least 3 dots padding on the longest test identifier)

To compute the max, pretty report need to iterate all suites/tests at the very beginning
